# Generated by Django 3.1 on 2020-08-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0004_tag_tag_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag_full_name',
            new_name='Full name tag',
        ),
    ]
