# Generated by Django 3.1 on 2020-08-11 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_auto_20200811_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='Full name tag',
            new_name='tag_full_name',
        ),
    ]
